default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bbusk
  passworld: 123456

development:
  <<: *default
  database: grandis_development

test:
  <<: *default
  database: grandis_test

production:
  <<: *default
  database: grandis_production
  username: grandis
  password: <%= ENV["GRANDIS_DATABASE_PASSWORD"] %>
